"""proactive leadership automation

Revision ID: 09c0bb98c92f
Revises: 925a7d2a72c7
Create Date: 2026-08-20 10:25:51.940059
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "09c0bb98c92f"
down_revision: str | None = "925a7d2a72c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.String(length=500), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_change_snapshots_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_change_snapshots_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_snapshots")),
        sa.UniqueConstraint(
            "tenant_id", "user_id", "subject_type", "subject_id", name="uq_change_snapshot_subject"
        ),
    )
    op.create_index(
        "ix_change_snapshots_scope_observed",
        "change_snapshots",
        ["tenant_id", "user_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_snapshots_tenant_id"), "change_snapshots", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_change_snapshots_user_id"), "change_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("daily_brief_enabled", sa.Boolean(), nullable=False),
        sa.Column("weekly_brief_enabled", sa.Boolean(), nullable=False),
        sa.Column("decision_reminders_enabled", sa.Boolean(), nullable=False),
        sa.Column("risk_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("minimum_level", sa.String(length=20), nullable=False),
        sa.Column("maximum_per_day", sa.Integer(), nullable=False),
        sa.Column("quiet_hours_start", sa.String(length=20), nullable=True),
        sa.Column("quiet_hours_end", sa.String(length=20), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_notification_preferences_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_preferences_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_notification_preferences_scope"),
    )
    op.create_index(
        op.f("ix_notification_preferences_tenant_id"),
        "notification_preferences",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "proactive_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("local_time", sa.String(length=20), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_proactive_schedules_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_proactive_schedules_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proactive_schedules")),
        sa.UniqueConstraint(
            "tenant_id",
            "user_id",
            "kind",
            name="uq_proactive_schedule_scope_kind",
        ),
    )
    op.create_index(
        "ix_proactive_schedules_due",
        "proactive_schedules",
        ["tenant_id", "user_id", "enabled", "next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proactive_schedules_enabled"), "proactive_schedules", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_proactive_schedules_kind"), "proactive_schedules", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_proactive_schedules_next_run_at"),
        "proactive_schedules",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proactive_schedules_tenant_id"), "proactive_schedules", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_proactive_schedules_user_id"), "proactive_schedules", ["user_id"], unique=False
    )
    op.create_table(
        "proactive_notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("dedupe_key", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("recommended_next_step", sa.Text(), nullable=False),
        sa.Column("related_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivery_channel", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["related_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_proactive_notifications_related_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_proactive_notifications_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_proactive_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proactive_notifications")),
        sa.UniqueConstraint("tenant_id", "user_id", "dedupe_key", name="uq_notification_dedupe"),
    )
    op.create_index(
        op.f("ix_proactive_notifications_category"),
        "proactive_notifications",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proactive_notifications_level"), "proactive_notifications", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_proactive_notifications_related_artifact_id"),
        "proactive_notifications",
        ["related_artifact_id"],
        unique=False,
    )
    op.create_index(
        "ix_proactive_notifications_scope_status",
        "proactive_notifications",
        ["tenant_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proactive_notifications_status"),
        "proactive_notifications",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proactive_notifications_tenant_id"),
        "proactive_notifications",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proactive_notifications_user_id"),
        "proactive_notifications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proactive_notifications_user_id"), table_name="proactive_notifications")
    op.drop_index(
        op.f("ix_proactive_notifications_tenant_id"), table_name="proactive_notifications"
    )
    op.drop_index(op.f("ix_proactive_notifications_status"), table_name="proactive_notifications")
    op.drop_index("ix_proactive_notifications_scope_status", table_name="proactive_notifications")
    op.drop_index(
        op.f("ix_proactive_notifications_related_artifact_id"), table_name="proactive_notifications"
    )
    op.drop_index(op.f("ix_proactive_notifications_level"), table_name="proactive_notifications")
    op.drop_index(op.f("ix_proactive_notifications_category"), table_name="proactive_notifications")
    op.drop_table("proactive_notifications")
    op.drop_index(op.f("ix_proactive_schedules_user_id"), table_name="proactive_schedules")
    op.drop_index(op.f("ix_proactive_schedules_tenant_id"), table_name="proactive_schedules")
    op.drop_index(op.f("ix_proactive_schedules_next_run_at"), table_name="proactive_schedules")
    op.drop_index(op.f("ix_proactive_schedules_kind"), table_name="proactive_schedules")
    op.drop_index(op.f("ix_proactive_schedules_enabled"), table_name="proactive_schedules")
    op.drop_index("ix_proactive_schedules_due", table_name="proactive_schedules")
    op.drop_table("proactive_schedules")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_index(
        op.f("ix_notification_preferences_tenant_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_change_snapshots_user_id"), table_name="change_snapshots")
    op.drop_index(op.f("ix_change_snapshots_tenant_id"), table_name="change_snapshots")
    op.drop_index("ix_change_snapshots_scope_observed", table_name="change_snapshots")
    op.drop_table("change_snapshots")
    # ### end Alembic commands ###
