"""mcp atlassian tool observability

Revision ID: 3b83e97ed121
Revises: f1ed15274e76
Create Date: 2026-08-20 09:00:06.336047
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3b83e97ed121"
down_revision: str | None = "f1ed15274e76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=500), nullable=True),
        sa.Column("tool_name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("capability", sa.String(length=200), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("contract_version", sa.String(length=50), nullable=False),
        sa.Column("adapter_version", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_tool_calls_tenant_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tool_calls_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    op.create_index(op.f("ix_tool_calls_run_id"), "tool_calls", ["run_id"], unique=False)
    op.create_index(
        "ix_tool_calls_run_started", "tool_calls", ["run_id", "started_at"], unique=False
    )
    op.create_index(
        "ix_tool_calls_scope_status", "tool_calls", ["tenant_id", "user_id", "status"], unique=False
    )
    op.create_index(op.f("ix_tool_calls_status"), "tool_calls", ["status"], unique=False)
    op.create_index(op.f("ix_tool_calls_tenant_id"), "tool_calls", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_tool_calls_tool_name"), "tool_calls", ["tool_name"], unique=False)
    op.create_index(op.f("ix_tool_calls_user_id"), "tool_calls", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_tool_calls_workspace_id"), "tool_calls", ["workspace_id"], unique=False
    )
    with op.batch_alter_table("agent_runs") as batch:
        batch.add_column(
            sa.Column(
                "tool_contract_version",
                sa.String(length=50),
                nullable=False,
                server_default="1.0.0",
            )
        )
        batch.add_column(
            sa.Column(
                "mcp_adapter_version",
                sa.String(length=50),
                nullable=False,
                server_default="1.0.0",
            )
        )
    with op.batch_alter_table("agent_runs") as batch:
        batch.alter_column("tool_contract_version", server_default=None)
        batch.alter_column("mcp_adapter_version", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_runs") as batch:
        batch.drop_column("mcp_adapter_version")
        batch.drop_column("tool_contract_version")
    op.drop_index(op.f("ix_tool_calls_workspace_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_user_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_tool_name"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_tenant_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_status"), table_name="tool_calls")
    op.drop_index("ix_tool_calls_scope_status", table_name="tool_calls")
    op.drop_index("ix_tool_calls_run_started", table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_run_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    # ### end Alembic commands ###
