"""management intelligence and attention

Revision ID: 925a7d2a72c7
Revises: b1b87af2a222
Create Date: 2026-08-20 09:56:48.615853
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "925a7d2a72c7"
down_revision: str | None = "b1b87af2a222"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initiatives",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("owner_ids", sa.JSON(), nullable=False),
        sa.Column("objective_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("product_outcomes", sa.JSON(), nullable=False),
        sa.Column("business_outcomes", sa.JSON(), nullable=False),
        sa.Column("decision_ids", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("artifact_ids", sa.JSON(), nullable=False),
        sa.Column("jira_issue_ids", sa.JSON(), nullable=False),
        sa.Column("dependency_ids", sa.JSON(), nullable=False),
        sa.Column("health", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_initiatives_tenant_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_initiatives_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_initiatives")),
    )
    op.create_index(
        "ix_initiatives_scope_status",
        "initiatives",
        ["tenant_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_initiatives_status"), "initiatives", ["status"], unique=False)
    op.create_index(op.f("ix_initiatives_tenant_id"), "initiatives", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_initiatives_updated_at"), "initiatives", ["updated_at"], unique=False)
    op.create_index(op.f("ix_initiatives_user_id"), "initiatives", ["user_id"], unique=False)
    op.create_table(
        "management_signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.String(length=500), nullable=False),
        sa.Column("epistemic_level", sa.String(length=50), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("derived_signal", sa.Text(), nullable=True),
        sa.Column("interpretation", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=False),
        sa.Column("significance", sa.String(length=30), nullable=False),
        sa.Column("time_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_management_signals_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_management_signals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_management_signals")),
    )
    op.create_index(
        "ix_management_signals_scope_status",
        "management_signals",
        ["tenant_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_management_signals_signal_type"),
        "management_signals",
        ["signal_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_management_signals_significance"),
        "management_signals",
        ["significance"],
        unique=False,
    )
    op.create_index(
        op.f("ix_management_signals_status"), "management_signals", ["status"], unique=False
    )
    op.create_index(
        "ix_management_signals_subject",
        "management_signals",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_management_signals_tenant_id"), "management_signals", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_management_signals_user_id"), "management_signals", ["user_id"], unique=False
    )
    op.create_table(
        "outcomes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("outcome_type", sa.String(length=30), nullable=False),
        sa.Column("baseline", sa.Text(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("current", sa.Text(), nullable=True),
        sa.Column("metric", sa.String(length=500), nullable=True),
        sa.Column("owner_ids", sa.JSON(), nullable=False),
        sa.Column("initiative_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attribution", sa.String(length=30), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_outcomes_tenant_id_organizations")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_outcomes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outcomes")),
    )
    op.create_index(op.f("ix_outcomes_outcome_type"), "outcomes", ["outcome_type"], unique=False)
    op.create_index(
        "ix_outcomes_scope_status", "outcomes", ["tenant_id", "user_id", "status"], unique=False
    )
    op.create_index(op.f("ix_outcomes_status"), "outcomes", ["status"], unique=False)
    op.create_index(op.f("ix_outcomes_tenant_id"), "outcomes", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_outcomes_updated_at"), "outcomes", ["updated_at"], unique=False)
    op.create_index(op.f("ix_outcomes_user_id"), "outcomes", ["user_id"], unique=False)
    op.create_table(
        "attention_signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("management_signal_id", sa.String(length=36), nullable=False),
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.String(length=500), nullable=False),
        sa.Column("level", sa.String(length=30), nullable=False),
        sa.Column("why_surfaced", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("recommended_next_step", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["management_signal_id"],
            ["management_signals.id"],
            name=op.f("fk_attention_signals_management_signal_id_management_signals"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_attention_signals_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attention_signals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attention_signals")),
    )
    op.create_index(
        "ix_attention_scope_status",
        "attention_signals",
        ["tenant_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attention_signals_level"), "attention_signals", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_attention_signals_management_signal_id"),
        "attention_signals",
        ["management_signal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attention_signals_status"), "attention_signals", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_attention_signals_tenant_id"), "attention_signals", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_attention_signals_user_id"), "attention_signals", ["user_id"], unique=False
    )
    op.create_table(
        "commitments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("initiative_id", sa.String(length=36), nullable=True),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiative_id"],
            ["initiatives.id"],
            name=op.f("fk_commitments_initiative_id_initiatives"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_commitments_tenant_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_commitments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commitments")),
    )
    op.create_index(op.f("ix_commitments_due_at"), "commitments", ["due_at"], unique=False)
    op.create_index(
        op.f("ix_commitments_initiative_id"), "commitments", ["initiative_id"], unique=False
    )
    op.create_index(op.f("ix_commitments_owner_id"), "commitments", ["owner_id"], unique=False)
    op.create_index(
        "ix_commitments_scope_status",
        "commitments",
        ["tenant_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_commitments_status"), "commitments", ["status"], unique=False)
    op.create_index(op.f("ix_commitments_tenant_id"), "commitments", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_commitments_updated_at"), "commitments", ["updated_at"], unique=False)
    op.create_index(op.f("ix_commitments_user_id"), "commitments", ["user_id"], unique=False)
    op.create_table(
        "management_signal_corrections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("signal_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("prior_interpretation", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["management_signals.id"],
            name=op.f("fk_management_signal_corrections_signal_id_management_signals"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_management_signal_corrections_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_management_signal_corrections")),
    )
    op.create_index(
        op.f("ix_management_signal_corrections_signal_id"),
        "management_signal_corrections",
        ["signal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_management_signal_corrections_user_id"),
        "management_signal_corrections",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_management_signal_corrections_user_id"), table_name="management_signal_corrections"
    )
    op.drop_index(
        op.f("ix_management_signal_corrections_signal_id"),
        table_name="management_signal_corrections",
    )
    op.drop_table("management_signal_corrections")
    op.drop_index(op.f("ix_commitments_user_id"), table_name="commitments")
    op.drop_index(op.f("ix_commitments_updated_at"), table_name="commitments")
    op.drop_index(op.f("ix_commitments_tenant_id"), table_name="commitments")
    op.drop_index(op.f("ix_commitments_status"), table_name="commitments")
    op.drop_index("ix_commitments_scope_status", table_name="commitments")
    op.drop_index(op.f("ix_commitments_owner_id"), table_name="commitments")
    op.drop_index(op.f("ix_commitments_initiative_id"), table_name="commitments")
    op.drop_index(op.f("ix_commitments_due_at"), table_name="commitments")
    op.drop_table("commitments")
    op.drop_index(op.f("ix_attention_signals_user_id"), table_name="attention_signals")
    op.drop_index(op.f("ix_attention_signals_tenant_id"), table_name="attention_signals")
    op.drop_index(op.f("ix_attention_signals_status"), table_name="attention_signals")
    op.drop_index(op.f("ix_attention_signals_management_signal_id"), table_name="attention_signals")
    op.drop_index(op.f("ix_attention_signals_level"), table_name="attention_signals")
    op.drop_index("ix_attention_scope_status", table_name="attention_signals")
    op.drop_table("attention_signals")
    op.drop_index(op.f("ix_outcomes_user_id"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_updated_at"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_tenant_id"), table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_status"), table_name="outcomes")
    op.drop_index("ix_outcomes_scope_status", table_name="outcomes")
    op.drop_index(op.f("ix_outcomes_outcome_type"), table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index(op.f("ix_management_signals_user_id"), table_name="management_signals")
    op.drop_index(op.f("ix_management_signals_tenant_id"), table_name="management_signals")
    op.drop_index("ix_management_signals_subject", table_name="management_signals")
    op.drop_index(op.f("ix_management_signals_status"), table_name="management_signals")
    op.drop_index(op.f("ix_management_signals_significance"), table_name="management_signals")
    op.drop_index(op.f("ix_management_signals_signal_type"), table_name="management_signals")
    op.drop_index("ix_management_signals_scope_status", table_name="management_signals")
    op.drop_table("management_signals")
    op.drop_index(op.f("ix_initiatives_user_id"), table_name="initiatives")
    op.drop_index(op.f("ix_initiatives_updated_at"), table_name="initiatives")
    op.drop_index(op.f("ix_initiatives_tenant_id"), table_name="initiatives")
    op.drop_index(op.f("ix_initiatives_status"), table_name="initiatives")
    op.drop_index("ix_initiatives_scope_status", table_name="initiatives")
    op.drop_table("initiatives")
    # ### end Alembic commands ###
