"""persistent intelligence foundation

Revision ID: a5f17a84db88
Revises:
Create Date: 2026-08-20 02:41:10.816165
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a5f17a84db88"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trace_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_events")),
    )
    op.create_index(
        op.f("ix_trace_events_event_type"), "trace_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_trace_events_run_id"), "trace_events", ["run_id"], unique=False)
    op.create_index(
        "ix_trace_events_run_occurred", "trace_events", ["run_id", "occurred_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("request", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("workflow", sa.String(length=100), nullable=False),
        sa.Column("runtime_version", sa.String(length=50), nullable=False),
        sa.Column("constitution_version", sa.String(length=50), nullable=False),
        sa.Column("memory_policy_version", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_runs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        op.f("ix_agent_runs_conversation_id"), "agent_runs", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_session_id"), "agent_runs", ["session_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_index(op.f("ix_agent_runs_user_id"), "agent_runs", ["user_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_conversations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_index(
        "ix_conversations_user_updated", "conversations", ["user_id", "updated_at"], unique=False
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("memory_type", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("normalized_content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.String(length=500), nullable=True),
        sa.Column("provenance_type", sa.String(length=30), nullable=False),
        sa.Column("memory_key", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(op.f("ix_memories_memory_type"), "memories", ["memory_type"], unique=False)
    op.create_index(op.f("ix_memories_status"), "memories", ["status"], unique=False)
    op.create_index(op.f("ix_memories_user_id"), "memories", ["user_id"], unique=False)
    op.create_index(
        "ix_memories_user_key_status", "memories", ["user_id", "memory_key", "status"], unique=False
    )
    op.create_index(
        "ix_memories_user_type_status",
        "memories",
        ["user_id", "memory_type", "status"],
        unique=False,
    )
    op.create_table(
        "working_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("workflow_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("open_questions", sa.JSON(), nullable=False),
        sa.Column("hypotheses", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("artifact_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_working_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_working_sessions")),
    )
    op.create_index(
        op.f("ix_working_sessions_status"), "working_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_working_sessions_user_id"), "working_sessions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_working_sessions_user_status", "working_sessions", ["user_id", "status"], unique=False
    )
    op.create_table(
        "beliefs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("supporting_evidence", sa.JSON(), nullable=False),
        sa.Column("contradicting_evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"], ["memories.id"], name=op.f("fk_beliefs_memory_id_memories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beliefs")),
    )
    op.create_index(op.f("ix_beliefs_memory_id"), "beliefs", ["memory_id"], unique=True)
    op.create_index(op.f("ix_beliefs_status"), "beliefs", ["status"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("alternatives", sa.JSON(), nullable=False),
        sa.Column("rejected_alternatives", sa.JSON(), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("tradeoffs", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_trigger", sa.Text(), nullable=True),
        sa.Column("validation_plan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"], ["memories.id"], name=op.f("fk_decisions_memory_id_memories")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_decisions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("memory_id", name=op.f("uq_decisions_memory_id")),
    )
    op.create_index(op.f("ix_decisions_status"), "decisions", ["status"], unique=False)
    op.create_index(op.f("ix_decisions_user_id"), "decisions", ["user_id"], unique=False)
    op.create_table(
        "memory_relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("from_memory_id", sa.String(length=36), nullable=False),
        sa.Column("to_memory_id", sa.String(length=36), nullable=False),
        sa.Column("relationship_type", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_relationships_from_memory_id_memories"),
        ),
        sa.ForeignKeyConstraint(
            ["to_memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_relationships_to_memory_id_memories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_relationships")),
        sa.UniqueConstraint(
            "from_memory_id", "to_memory_id", "relationship_type", name="uq_memory_relationship"
        ),
    )
    op.create_index(
        op.f("ix_memory_relationships_from_memory_id"),
        "memory_relationships",
        ["from_memory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_relationships_to_memory_id"),
        "memory_relationships",
        ["to_memory_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_run_id"), "messages", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_run_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_memory_relationships_to_memory_id"), table_name="memory_relationships")
    op.drop_index(op.f("ix_memory_relationships_from_memory_id"), table_name="memory_relationships")
    op.drop_table("memory_relationships")
    op.drop_index(op.f("ix_decisions_user_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_status"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_beliefs_status"), table_name="beliefs")
    op.drop_index(op.f("ix_beliefs_memory_id"), table_name="beliefs")
    op.drop_table("beliefs")
    op.drop_index("ix_working_sessions_user_status", table_name="working_sessions")
    op.drop_index(op.f("ix_working_sessions_user_id"), table_name="working_sessions")
    op.drop_index(op.f("ix_working_sessions_status"), table_name="working_sessions")
    op.drop_table("working_sessions")
    op.drop_index("ix_memories_user_type_status", table_name="memories")
    op.drop_index("ix_memories_user_key_status", table_name="memories")
    op.drop_index(op.f("ix_memories_user_id"), table_name="memories")
    op.drop_index(op.f("ix_memories_status"), table_name="memories")
    op.drop_index(op.f("ix_memories_memory_type"), table_name="memories")
    op.drop_table("memories")
    op.drop_index("ix_conversations_user_updated", table_name="conversations")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_agent_runs_user_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_session_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_conversation_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("users")
    op.drop_index("ix_trace_events_run_occurred", table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_run_id"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_event_type"), table_name="trace_events")
    op.drop_table("trace_events")
    # ### end Alembic commands ###
