"""product intelligence workflows and artifacts

Revision ID: b1b87af2a222
Revises: 3b83e97ed121
Create Date: 2026-08-20 09:29:37.227903
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b1b87af2a222"
down_revision: str | None = "3b83e97ed121"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("rendered_content", sa.Text(), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_name", sa.String(length=100), nullable=False),
        sa.Column("workflow_version", sa.String(length=50), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("working_session_id", sa.String(length=36), nullable=True),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("memory_ids", sa.JSON(), nullable=False),
        sa.Column("model_metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], name=op.f("fk_artifacts_agent_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_artifacts_tenant_id_organizations")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_artifacts_user_id_users")),
        sa.ForeignKeyConstraint(
            ["working_session_id"],
            ["working_sessions.id"],
            name=op.f("fk_artifacts_working_session_id_working_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(op.f("ix_artifacts_agent_run_id"), "artifacts", ["agent_run_id"], unique=False)
    op.create_index(
        op.f("ix_artifacts_artifact_type"), "artifacts", ["artifact_type"], unique=False
    )
    op.create_index(
        "ix_artifacts_scope_type",
        "artifacts",
        ["tenant_id", "user_id", "artifact_type"],
        unique=False,
    )
    op.create_index(
        "ix_artifacts_scope_updated",
        "artifacts",
        ["tenant_id", "user_id", "updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_artifacts_status"), "artifacts", ["status"], unique=False)
    op.create_index(op.f("ix_artifacts_tenant_id"), "artifacts", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_artifacts_user_id"), "artifacts", ["user_id"], unique=False)
    op.create_index(op.f("ix_artifacts_workflow_id"), "artifacts", ["workflow_id"], unique=False)
    op.create_index(
        op.f("ix_artifacts_workflow_name"), "artifacts", ["workflow_name"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_working_session_id"), "artifacts", ["working_session_id"], unique=False
    )
    with op.batch_alter_table("agent_runs") as batch:
        batch.add_column(
            sa.Column(
                "workflow_version",
                sa.String(length=50),
                nullable=False,
                server_default="1.0.0",
            )
        )
        batch.add_column(
            sa.Column(
                "prompt_versions",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'{}'"),
            )
        )
    with op.batch_alter_table("agent_runs") as batch:
        batch.alter_column("workflow_version", server_default=None)
        batch.alter_column("prompt_versions", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_runs") as batch:
        batch.drop_column("prompt_versions")
        batch.drop_column("workflow_version")
    op.drop_index(op.f("ix_artifacts_working_session_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_workflow_name"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_workflow_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_user_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_tenant_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_status"), table_name="artifacts")
    op.drop_index("ix_artifacts_scope_updated", table_name="artifacts")
    op.drop_index("ix_artifacts_scope_type", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_artifact_type"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_agent_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
