"""evidence first knowledge retrieval

Revision ID: f1ed15274e76
Revises: a5f17a84db88
Create Date: 2026-08-20 08:37:29.989797
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

from productos.infrastructure.persistence.models import VectorStorage

revision: str = "f1ed15274e76"
down_revision: str | None = "a5f17a84db88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    connection = op.get_bind()
    if connection.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "knowledge_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.Column("document_format", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("owner", sa.String(length=500), nullable=True),
        sa.Column("workspace", sa.String(length=500), nullable=True),
        sa.Column("project", sa.String(length=500), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("authority_score", sa.Float(), nullable=False),
        sa.Column("sensitivity", sa.String(length=30), nullable=False),
        sa.Column("access_boundary", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("embedding_provider", sa.String(length=200), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["knowledge_items.id"],
            name=op.f("fk_knowledge_items_supersedes_id_knowledge_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_items_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_knowledge_items_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_items")),
    )
    op.create_index(
        op.f("ix_knowledge_items_project"), "knowledge_items", ["project"], unique=False
    )
    op.create_index(
        "ix_knowledge_items_scope_source",
        "knowledge_items",
        ["tenant_id", "user_id", "source_type", "source_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_items_scope_status",
        "knowledge_items",
        ["tenant_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_items_source_id"), "knowledge_items", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_source_type"), "knowledge_items", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_knowledge_items_status"), "knowledge_items", ["status"], unique=False)
    op.create_index(
        op.f("ix_knowledge_items_supersedes_id"), "knowledge_items", ["supersedes_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_tenant_id"), "knowledge_items", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_user_id"), "knowledge_items", ["user_id"], unique=False
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_item_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", VectorStorage(128), nullable=False),
        sa.Column("section_title", sa.String(length=1000), nullable=True),
        sa.Column("parent_section", sa.String(length=1000), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_item_id"],
            ["knowledge_items.id"],
            name=op.f("fk_knowledge_chunks_knowledge_item_id_knowledge_items"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_chunks_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_knowledge_chunks_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint("knowledge_item_id", "chunk_index", name="uq_knowledge_chunk_index"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_knowledge_item_id"),
        "knowledge_chunks",
        ["knowledge_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_chunks_scope", "knowledge_chunks", ["tenant_id", "user_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_tenant_id"), "knowledge_chunks", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_user_id"), "knowledge_chunks", ["user_id"], unique=False
    )
    default_tenant = "00000000-0000-4000-8000-000000000010"
    op.bulk_insert(
        sa.table(
            "organizations",
            sa.column("id", sa.String()),
            sa.column("name", sa.String()),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": default_tenant,
                "name": "Default organization",
                "created_at": datetime.now(UTC),
            }
        ],
    )
    with op.batch_alter_table("agent_runs") as batch:
        batch.add_column(
            sa.Column(
                "tenant_id", sa.String(length=36), nullable=False, server_default=default_tenant
            )
        )
        batch.add_column(
            sa.Column(
                "retrieval_policy_version",
                sa.String(length=50),
                nullable=False,
                server_default="1.0.0",
            )
        )
        batch.create_index(op.f("ix_agent_runs_tenant_id"), ["tenant_id"], unique=False)
        batch.create_foreign_key(
            op.f("fk_agent_runs_tenant_id_organizations"),
            "organizations",
            ["tenant_id"],
            ["id"],
        )
    with op.batch_alter_table("agent_runs") as batch:
        batch.alter_column("tenant_id", server_default=None)
        batch.alter_column("retrieval_policy_version", server_default=None)
    if connection.dialect.name == "postgresql":
        op.create_index(
            "ix_knowledge_chunks_content_fts",
            "knowledge_chunks",
            [sa.text("to_tsvector('english'::regconfig, content)")],
            postgresql_using="gin",
        )
        op.create_index(
            "ix_knowledge_chunks_embedding_hnsw",
            "knowledge_chunks",
            ["embedding"],
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    if connection.dialect.name == "postgresql":
        op.drop_index("ix_knowledge_chunks_embedding_hnsw", table_name="knowledge_chunks")
        op.drop_index("ix_knowledge_chunks_content_fts", table_name="knowledge_chunks")
    with op.batch_alter_table("agent_runs") as batch:
        batch.drop_constraint(op.f("fk_agent_runs_tenant_id_organizations"), type_="foreignkey")
        batch.drop_index(op.f("ix_agent_runs_tenant_id"))
        batch.drop_column("retrieval_policy_version")
        batch.drop_column("tenant_id")
    op.drop_index(op.f("ix_knowledge_chunks_user_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_tenant_id"), table_name="knowledge_chunks")
    op.drop_index("ix_knowledge_chunks_scope", table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_knowledge_item_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_items_user_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_tenant_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_supersedes_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_status"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_source_type"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_source_id"), table_name="knowledge_items")
    op.drop_index("ix_knowledge_items_scope_status", table_name="knowledge_items")
    op.drop_index("ix_knowledge_items_scope_source", table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_project"), table_name="knowledge_items")
    op.drop_table("knowledge_items")
    op.drop_table("organizations")
    # ### end Alembic commands ###
